'use client';

import Link from 'next/link';
import { ArrowUpRight, Menu, ShoppingBag, Sparkles } from 'lucide-react';
import { useCartStore } from '@/src/store/useCartStore';

export default function StorefrontHeader() {
  const itemCount = useCartStore((state) => state.items.reduce((total, item) => total + item.design.quantity, 0));
  return <header className="pointer-events-none fixed inset-x-0 top-0 z-50 px-3 pt-3 sm:px-6 sm:pt-5"><div className="pointer-events-auto mx-auto flex h-14 max-w-6xl items-center justify-between rounded-2xl border border-white/70 bg-white/65 px-3 shadow-[0_12px_32px_rgba(109,88,150,.12)] backdrop-blur-xl sm:h-16 sm:px-4"><Link href="/" className="group flex items-center gap-2.5 font-bold tracking-[-.04em] text-slate-800"><span className="grid h-8 w-8 place-items-center rounded-xl bg-gradient-to-br from-violet-400 via-violet-500 to-indigo-500 text-white shadow-lg shadow-violet-300/50 transition-transform duration-300 group-hover:rotate-12"><Sparkles size={16} /></span><span className="text-lg">Style<span className="text-violet-600">Cute</span></span></Link><nav className="hidden items-center gap-7 text-sm font-medium text-slate-500 md:flex"><a href="#catalogo" className="transition hover:text-violet-700">Catálogo</a><a href="#como-funciona" className="transition hover:text-violet-700">Cómo funciona</a><a href="#inspiracion" className="transition hover:text-violet-700">Inspiración</a></nav><div className="flex items-center gap-1.5"><button type="button" onClick={() => window.dispatchEvent(new CustomEvent('store:open-cart'))} className="relative inline-flex h-9 items-center gap-2 rounded-xl border border-violet-100 bg-violet-50/80 px-2.5 text-sm font-semibold text-slate-700 transition hover:bg-violet-100 sm:h-10 sm:px-3" aria-label={`Abrir carrito, ${itemCount} productos`}><ShoppingBag size={17} /><span className="hidden sm:inline">Carrito</span>{itemCount > 0 && <span className="grid h-5 min-w-5 place-items-center rounded-full bg-violet-500 px-1 text-[10px] font-bold text-white">{itemCount}</span>}</button><Link href="#catalogo" className="hidden h-10 items-center gap-1 rounded-xl bg-slate-800 px-3 text-xs font-bold text-white transition hover:bg-violet-600 sm:inline-flex">Crear <ArrowUpRight size={14} /></Link><button type="button" className="rounded-lg p-2 text-slate-600 md:hidden" aria-label="Abrir menú"><Menu size={19} /></button></div></div></header>;
}
